# Makefile for Beginning Linux Programming 3rd Edition
# Chapter 5

MENU=menu1 menu2 menu3 menu4

TERMIOS=password

ALL= $(MENU) $(TERMIOS)

menu: $(MENU)

termios: $(TERMIOS)

all: $(ALL)

clean:
	@rm -f $(ALL) *~
